### ISSUE TITLE
Update Node Version

### ISSUE THREAD

**Issue by JordanForeman** [JordanForeman/cf-find#470]
This project is quite old. The `.nvmrc` indicates this works on `Node@10`. 

- [ ] Update to the latest `lts` (`lts/hydrogen` at the time of this writing). 

See also: https://nodejs.dev/en/about/releases/

**Comment by tiago154** [comment]
Hello, I would like to do this task

**Comment by JordanForeman** [comment]
@tiago154 that was quick! It's yours. I'm working on updating some of the contribution documentation, but in the meantime just use your best judgment. I'll keep an eye out for your PR.

There may be some complications as a lot of this codebase's dependencies are out of date and may need updated (or even replaces) to support the latest node version. Hopefully this is a simple enough change 😅

**Comment by JordanForeman** [comment]
Fixed in #474

**Comment by JordanForeman** [comment]
@tiago154 let me know if you don't get Hacktoberfest credit for any reason. Hopefully I've got all the labels configured correctly

**Comment by tiago154** [comment]
@JordanForeman I'm participating in hacktoberfest and everything is fine.
Thank you very much
